services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chihougo-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: chihougo-frontend
    ports:
      - "5101:5101"

    restart: unless-stopped

networks:
  default:
    name: chihougo-network
